/home/mei/anaconda2/lib/python2.7/site-packages/openpyxl/xml/functions.py:31: DeprecationWarning: defusedxml.lxml is no longer supported and will be removed in a future release.
/home/mei/anaconda2/lib/python2.7/site-packages/agate/utils.py:301: DuplicateColumnWarning: Column name "Num" already exists in Table. Column will be renamed to "Num_2".
/home/mei/anaconda2/lib/python2.7/site-packages/agate/utils.py:301: DuplicateColumnWarning: Column name "Code" already exists in Table. Column will be renamed to "Code_2".
/home/mei/anaconda2/lib/python2.7/site-packages/agate/utils.py:301: DuplicateColumnWarning: Column name "Num" already exists in Table. Column will be renamed to "Num_3".
/home/mei/anaconda2/lib/python2.7/site-packages/agate/utils.py:301: DuplicateColumnWarning: Column name "Code" already exists in Table. Column will be renamed to "Code_3".
/home/mei/anaconda2/lib/python2.7/site-packages/agate/utils.py:301: DuplicateColumnWarning: Column name "Num" already exists in Table. Column will be renamed to "Num_4".
/home/mei/anaconda2/lib/python2.7/site-packages/agate/utils.py:301: DuplicateColumnWarning: Column name "Code" already exists in Table. Column will be renamed to "Code_4".
/home/mei/anaconda2/lib/python2.7/site-packages/agate/utils.py:285: UnnamedColumnWarning: Column 26 has no name. Using "aa".
/home/mei/anaconda2/lib/python2.7/site-packages/agate/utils.py:285: UnnamedColumnWarning: Column 27 has no name. Using "bb".
/home/mei/anaconda2/lib/python2.7/site-packages/agate/utils.py:285: UnnamedColumnWarning: Column 28 has no name. Using "cc".
/home/mei/anaconda2/lib/python2.7/site-packages/agate/utils.py:285: UnnamedColumnWarning: Column 29 has no name. Using "dd".
/home/mei/anaconda2/lib/python2.7/site-packages/agate/utils.py:285: UnnamedColumnWarning: Column 30 has no name. Using "ee".
/home/mei/anaconda2/lib/python2.7/site-packages/agate/utils.py:285: UnnamedColumnWarning: Column 31 has no name. Using "ff".
/home/mei/anaconda2/lib/python2.7/site-packages/agate/utils.py:285: UnnamedColumnWarning: Column 32 has no name. Using "gg".
/home/mei/anaconda2/lib/python2.7/site-packages/agate/utils.py:285: UnnamedColumnWarning: Column 33 has no name. Using "hh".
/home/mei/anaconda2/lib/python2.7/site-packages/agate/utils.py:285: UnnamedColumnWarning: Column 34 has no name. Using "ii".
/home/mei/anaconda2/lib/python2.7/site-packages/agate/utils.py:285: UnnamedColumnWarning: Column 35 has no name. Using "jj".
/home/mei/anaconda2/lib/python2.7/site-packages/agate/utils.py:285: UnnamedColumnWarning: Column 36 has no name. Using "kk".
/home/mei/anaconda2/lib/python2.7/site-packages/agate/utils.py:285: UnnamedColumnWarning: Column 37 has no name. Using "ll".
/home/mei/anaconda2/lib/python2.7/site-packages/agate/utils.py:285: UnnamedColumnWarning: Column 38 has no name. Using "mm".
/home/mei/anaconda2/lib/python2.7/site-packages/agate/utils.py:285: UnnamedColumnWarning: Column 39 has no name. Using "nn".
/home/mei/anaconda2/lib/python2.7/site-packages/agate/utils.py:285: UnnamedColumnWarning: Column 40 has no name. Using "oo".
/home/mei/anaconda2/lib/python2.7/site-packages/agate/utils.py:285: UnnamedColumnWarning: Column 41 has no name. Using "pp".
/home/mei/anaconda2/lib/python2.7/site-packages/agate/utils.py:285: UnnamedColumnWarning: Column 42 has no name. Using "qq".
/home/mei/anaconda2/lib/python2.7/site-packages/agate/utils.py:285: UnnamedColumnWarning: Column 43 has no name. Using "rr".
/home/mei/anaconda2/lib/python2.7/site-packages/agate/utils.py:285: UnnamedColumnWarning: Column 44 has no name. Using "ss".
/home/mei/anaconda2/lib/python2.7/site-packages/agate/utils.py:285: UnnamedColumnWarning: Column 45 has no name. Using "tt".
